name: Auto-triage to project boards

on:
  issues:
    types: [opened, labeled]
  pull_request_target:
    types: [opened, labeled]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  COLUMN_NAME: Needs Triage # column where issues will be created

jobs:
  content_project:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: 11873277
      PROJECT_NAME: Docs PRs and Issues
    name: Triage to Content Project
    steps:
    - name: Triages NEW issues and NEW pull requests to the Content Project
      if: github.event.action == 'opened'
      run: |
        echo "PR id is: ${{ github.event.issue.number}}"
        HEADER="Accept: application/vnd.github.inertia-preview+json"
        PROJECT=$(gh api -H "$HEADER" repos/:owner/:repo/projects --jq ".[] | select(.id == \"${{ env.PROJECT_ID }}\").id")
        COLUMN=$(gh api -H "$HEADER" "projects/$PROJECT/columns" --jq ".[] | select(.name == \"${{ env.COLUMN_NAME }}\").id")
        gh api -H "$HEADER" -X POST "projects/columns/$COLUMN/cards" -f content_type='PullRequest' -F content_id=${{ github.event.issue.number }}

  localization_project:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: 12004783
      PROJECT_NAME: Docs Site Localization PRs and Issues
    name: Triage to Localization Project
    steps:
    - name: Triages NEW issues and NEW pull requests to the Localization Project
      if: |
        contains(github.event.issue.labels.*.name, 'localization') ||
        contains(github.event.pull_request.labels.*.name, 'localization')
      run: |
        echo "PR id is: ${{ github.event.issue.number}}"
        HEADER="Accept: application/vnd.github.inertia-preview+json"
        PROJECT=$(gh api -H "$HEADER" repos/:owner/:repo/projects --jq ".[] | select(.id == \"${{ env.PROJECT_ID }}\").id")
        COLUMN=$(gh api -H "$HEADER" "projects/$PROJECT/columns" --jq ".[] | select(.name == \"${{ env.COLUMN_NAME }}\").id")
        gh api -H "$HEADER" -X POST "projects/columns/$COLUMN/cards" -f content_type='PullRequest' -F content_id=${{ github.event.issue.number }}
